FROM ubuntu:xenial

WORKDIR /usr/src

COPY etc/sources-xenial.list /etc/apt/sources.list
RUN apt-get update; \
    apt-get install -y python python-opencv python-mysqldb python-matplotlib; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

CMD ["python", "/usr/local/match.py"]
