version: "2.2"
services:
    im-render:
        image: "atw527/im-render"
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.render
        volumes:
            - /etc/hostname:/etc/docker_hostname:ro
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
            - ./src/render:/usr/local/bin:ro
            - ./data:/usr/local/data
        environment:
            MASTER: "server-13"
            MYSQL_HOST: "a01-mysql-01"
            MYSQL_PORT: 3306
            MYSQL_DB: "image_match"
            MYSQL_USER: "root"
            MYSQL_PASS: "q1w2e3r4"
        command: ["bash", "/usr/local/bin/render-forever.sh"]
