version: "2.2"
services:
    im-front:
        image: "atw527/im-front"
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.front
        volumes:
            - /etc/hostname:/etc/docker_hostname:ro
            - ./etc/php.ini:/etc/php/7.0/apache2/php.ini:ro
            - ./etc/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
            - ./src/front:/var/www/html:ro
            - ./data:/usr/local/data
        environment:
            MASTER: "server-13"
            MYSQL_HOST: "a01-mysql-01"
            MYSQL_PORT: 3306
            MYSQL_DB: "image_match"
            MYSQL_USER: "root"
            MYSQL_PASS: "q1w2e3r4"
        expose:
            - "80"
        ports:
            - "4280:80"
