version: "2"
services:
    testdata:
        image: "ubuntu:xenial"
        volumes:
            - ./testdata/content:/testdata
            - ./testdata/bin:/usr/local/bin
        command: ["bash", "/usr/local/bin/run.sh"]
