version: "2"
services:
    front:
        image: "atw527/image-match:front"
        build:
            context: .
            dockerfile: Dockerfile-front
        expose:
            - "80"
        ports:
            - "8088:80"
        volumes:
            - ./front:/var/www/html
            - ./data:/usr/local/data
            - ./etc/php.ini:/etc/php/7.0/apache2/php.ini
            - ./etc/000-default.conf:/etc/apache2/sites-available/000-default.conf
