FROM ubuntu:xenial

WORKDIR /usr/local

COPY etc/sources-xenial.list /etc/apt/sources.list
RUN apt-get update; \
    apt-get install -y curl ffmpeg python expect; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl; \
    chmod a+rx /usr/local/bin/youtube-dl

CMD ["bash", "/usr/local/bin/video_download.sh"]
