FROM ubuntu:xenial

WORKDIR /usr/local

COPY etc/sources-xenial.list /etc/apt/sources.list
RUN apt-get update; \
    apt-get install -y curl ffmpeg python python-mysqldb python-matplotlib expect rsync ssh php php-mysql imagemagick; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

COPY etc/ssh_config /root/.ssh/config
RUN chown -R root: /root/.ssh
RUN chmod 0600 /root/.ssh/*

CMD ["bash", "/usr/local/bin/video-process.py"]
