version: "2.2"
services:
    tmp-render:
        image: "atw527/image-match:tmp-render"
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-tmp-render
        volumes:
            - /etc/hostname:/etc/docker_hostname:ro
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
            - ./data:/usr/local
        command: ["python", "/usr/local/bin/video-process.py"]
