FROM ubuntu:xenial

WORKDIR /usr/local

COPY etc/ssh_config /root/.ssh/config
RUN chown -R root: /root/.ssh
RUN chmod 0600 /root/.ssh/*

COPY etc/sources-xenial.list /etc/apt/sources.list
RUN apt-get update; \
    apt-get install -y curl ffmpeg python expect rsync ssh php php-mysql imagemagick; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

CMD ["bash", "/usr/local/bin/tmp-frame-process.php"]
