FROM ubuntu:xenial

WORKDIR /usr/local

COPY etc/sources-xenial.list /etc/apt/sources.list
RUN apt-get update; \
    apt-get install -y python wget python-opencv python-mysqldb python-matplotlib; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

COPY etc/ssh_config /root/.ssh/config
RUN chown -R root: /root/.ssh
RUN chmod 0600 /root/.ssh/*

CMD ["python", "/usr/local/match.py"]
