version: "2"
services:
    testdata:
        image: "ubuntu:xenial"
        volumes:
            - ./test/data:/usr/test
            - ./test/bin:/usr/local/bin
        command: ["bash", "/usr/local/bin/run.sh"]
