version: "2"
services:
    im-download:
        image: "atw527/im-download"
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.download
        volumes:
            - /etc/hostname:/etc/docker_hostname:ro
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
            - ./data:/usr/local/data
            - ./src/download:/usr/local/bin
        environment:
            MASTER: "server-13"
            MYSQL_HOST: "a01-mysql-01"
            MYSQL_PORT: 3306
            MYSQL_USER: "root"
            MYSQL_PASS: "q1w2e3r4"
        command: ["bash", "/usr/local/bin/download-forever.sh"]
